// ============================================================================
// Cheers for Phương — written by hand, in her voice, kept verbatim.
//
// Three "senses": warm encouragement, playful/funny, and random-flavored
// (gaming / anime / BA in-jokes). The study companion pulls from these for the
// motivational toasts. Only the cheers are Vietnamese; the rest of the UI is
// English. Personalization is already baked in (they greet Phương directly).
// ============================================================================

/** 100 warm, tender encouragements. */
export const CHEERS_WARM: string[] = [
  'Phương ơi, hôm nay cố gắng thêm một chút nhé! 🌸',
  'Mỗi trang tài liệu Phương đọc hôm nay đều đưa em đến gần ước mơ hơn.',
  'Phương giỏi hơn em nghĩ rất nhiều đấy.',
  'Chỉ cần tiến bộ 1% mỗi ngày là đủ rồi.',
  'Nghỉ một ngụm nước rồi tiếp tục nha, Phương. 🥤',
  'Anh tin Phương sẽ làm được.',
  'Đừng sợ sai, vì mỗi lần sai là một lần học.',
  'Hôm nay học một chút, ngày mai tự tin hơn rất nhiều.',
  'Cố lên Phương, tương lai đang chờ em.',
  'Em đang xây dựng phiên bản tốt nhất của chính mình.',
  'Đừng bỏ cuộc khi chỉ còn một chút nữa thôi.',
  'Học xong phần này rồi mình thưởng cho bản thân nhé.',
  'Phương chăm chỉ như vậy, kết quả đẹp chắc chắn sẽ đến.',
  'Một bài học hôm nay sẽ tiết kiệm rất nhiều thời gian sau này.',
  'Tin vào chính mình nhé, Phương.',
  'Không cần hoàn hảo, chỉ cần không dừng lại.',
  'Em đang làm rất tốt rồi.',
  'Hít một hơi thật sâu và tiếp tục nào.',
  'Chặng đường dài được tạo nên từ những bước nhỏ.',
  'Anh luôn tự hào về sự cố gắng của Phương.',
  'Mỗi phút tập trung đều đáng giá.',
  'Đừng nhìn quãng đường còn lại, hãy nhìn đoạn đường em đã đi.',
  'Phương cố lên, em gần xong rồi!',
  'Tương lai sẽ cảm ơn sự chăm chỉ của em hôm nay.',
  'Một chút nữa thôi, em làm được mà.',
  'Em mạnh mẽ hơn những gì em nghĩ.',
  'Đừng để một bài khó làm em nản lòng.',
  'Mỗi lần học là một lần trưởng thành.',
  'Anh luôn tin vào khả năng của Phương.',
  'Hôm nay học tốt, cuối tuần sẽ nghỉ thật vui.',
  'Đừng quên mỉm cười nhé. 😊',
  'Cố gắng hôm nay là món quà cho ngày mai.',
  'Phương là người rất kiên trì.',
  'Đừng so sánh với người khác, hãy so với chính mình của hôm qua.',
  'Em đang tiến bộ từng ngày.',
  'Chỉ cần thêm 10 phút nữa thôi!',
  'Học xong chương này mình nghỉ nhé.',
  'Anh biết em sẽ vượt qua được.',
  'Em xứng đáng với những điều tốt đẹp.',
  'Cứ bình tĩnh, từng bước một.',
  'Hôm nay học chăm, mai sẽ tự tin.',
  'Kiến thức không bao giờ phản bội sự nỗ lực.',
  'Phương tuyệt lắm! 🌷',
  'Đừng quên uống nước nha.',
  'Nghỉ mắt 30 giây rồi học tiếp nhé.',
  'Anh đang cổ vũ em từ xa. 💖',
  'Mỗi dòng ghi chú đều rất có giá trị.',
  'Em đang tiến gần mục tiêu BA từng ngày.',
  'Cứ tiếp tục, đừng dừng lại.',
  'Em làm tốt hơn hôm qua rồi.',
  'Đừng lo nếu chưa hiểu ngay, rồi sẽ hiểu thôi.',
  'Học từng chút cũng là học.',
  'Chỉ cần em không bỏ cuộc.',
  'Phương sẽ trở thành một Business Analyst thật giỏi.',
  'Hãy tự hào vì em đã bắt đầu.',
  'Cố lên cô gái chăm chỉ!',
  'Em có thể làm được những điều khó hơn em tưởng.',
  'Chỉ còn vài phút tập trung nữa thôi.',
  'Mỗi bài tập hoàn thành đều là một chiến thắng nhỏ.',
  'Anh thích nhìn thấy em chăm chỉ như thế.',
  'Phương đang gieo những hạt giống cho thành công.',
  'Đừng quên thư giãn một chút sau khi học.',
  'Hãy kiên nhẫn với bản thân.',
  'Không ai giỏi ngay từ đầu cả.',
  'Em đang đi đúng hướng.',
  'Mỗi ngày học là một ngày đáng tự hào.',
  'Cố lên nhé, anh luôn ủng hộ em.',
  'Hôm nay là một ngày tuyệt vời để học điều mới.',
  'Đừng để khó khăn làm em chùn bước.',
  'Em đã vượt qua rất nhiều rồi.',
  'Chỉ cần tiếp tục thôi.',
  'Một chương nữa là xong!',
  'Anh tin em sẽ đạt mục tiêu.',
  'Em đang làm rất tuyệt.',
  'Đừng quên nghỉ giải lao đúng lúc.',
  'Chúc em có một phiên học thật hiệu quả.',
  'Em chính là động lực của chính mình.',
  'Mỗi lần mở sách là một lần tiến bộ.',
  'Phương xứng đáng với thành công.',
  'Kiên trì chính là siêu năng lực của em.',
  'Chỉ cần hôm nay tốt hơn hôm qua.',
  'Anh luôn đứng về phía em.',
  'Hãy tiếp tục viết nên câu chuyện thành công của mình.',
  'Đừng sợ những thử thách khó.',
  'Em càng học, em càng tự tin.',
  'Một chút cố gắng nữa thôi nhé.',
  'Hôm nay học chăm, mai cười thật tươi.',
  'Phương là cô gái rất đáng ngưỡng mộ.',
  'Em đang tiến từng bước vững chắc.',
  'Đừng quên tự khen mình sau mỗi buổi học.',
  'Chúc em luôn giữ được ngọn lửa học tập.',
  'Em đã làm rất tốt rồi.',
  'Hãy tiếp tục với nụ cười nhé. 🌸',
  'Anh biết em sẽ không bỏ cuộc.',
  'Phương ơi, cố lên nhé! 💕',
  'Mỗi ngày đều là một cơ hội mới.',
  'Em đang tạo nên tương lai của chính mình.',
  'Chỉ cần bền bỉ, thành công sẽ đến.',
  'Học hết phiên này rồi mình nghỉ nhé.',
  'Anh luôn tin rằng Phương sẽ trở thành phiên bản tuyệt vời nhất của chính mình. 🌷✨',
]

/** 100 playful, funny nudges. */
export const CHEERS_FUNNY: string[] = [
  '🚨 Cảnh báo! Phương vừa tăng +5 IQ sau 10 phút học!',
  'BA tương lai điểm danh! Học tiếp thôi nào. 📚',
  'Máy chủ báo: "Độ chăm chỉ của Phương đang vượt ngưỡng." 💻',
  'Học xong chương này anh thưởng... một cái ôm ảo nhé! 🤗',
  'Não đang tải kiến thức... ███████░ 82%',
  'Nếu hôm nay học chăm, trà sữa ngày mai sẽ ngon hơn. 🧋',
  'Cố lên Phương! Deadline không biết thương ai đâu. 😂',
  'Có người đang âm thầm tự hào vì Phương đó. ❤️',
  'Đừng để con mèo trong đầu bảo "mai học". 😼',
  'Boss cuối của hôm nay chỉ là một chương học thôi!',
  'BA không tự nhiên mà giỏi... nhưng Phương thì có tiềm năng. 😎',
  'Học xong nhớ đứng dậy vươn vai, không là hóa tượng luôn đó.',
  'Tin nóng: Người chăm nhất hôm nay tên là Phương.',
  'Cà phê: "Tôi chỉ hỗ trợ thôi, còn lại là do Phương." ☕',
  'Não: "Thêm 15 phút nữa nha, tôi còn chạy tốt."',
  'Chương này không khó, chỉ đang giả vờ thôi.',
  'Đừng lo, Google cũng từng không biết đáp án. 😆',
  'Có một BA siêu ngầu đang được xây dựng...',
  'Achievement Unlocked: Không ngủ gật trong 30 phút! 🏆',
  'Phương vừa đánh bại quái vật "Lười biếng".',
  'Học xong rồi muốn làm gì cũng được... nhưng học xong đã.',
  'Chúc mừng! Bạn vừa sống sót qua thêm một slide PowerPoint.',
  'Trái tim nói nhớ ngủ, bộ não nói học tiếp. ❤️🧠',
  'Học đi, tương lai đang refresh rồi.',
  'Nếu kiến thức là Pokémon thì Phương đang bắt hết rồi.',
  'Ctrl + S cuộc đời bằng cách học thêm hôm nay.',
  'Loading... Đang cài đặt chế độ "Business Analyst Pro".',
  'Đừng sợ sai. Excel cũng đầy lỗi mà vẫn nổi tiếng.',
  'Chỉ cần học tiếp, còn drama để sau.',
  'Tin vui: Mỗi phút học đều cộng EXP.',
  'Hôm nay cố thêm chút, mai đỡ "toang".',
  'Não gửi lời cảm ơn vì chưa bị TikTok bắt cóc.',
  'Phương vừa né thành công một cú "để mai học".',
  'Hãy chứng minh cho chiếc ghế thấy nó không vô dụng.',
  'Bàn học nhớ Phương lắm rồi.',
  'Laptop đang rất tự hào về chủ nhân của mình.',
  'Chuột máy tính nói: "Click tiếp đi!"',
  'Chương này không cắn đâu.',
  'Cứ học đi, meme vẫn ở đó chờ em.',
  'Anh cá là Phương sẽ hiểu bài này.',
  'Học xong chương này level tăng ngay.',
  'Đừng lo, não có chế độ tự tối ưu sau khi ngủ.',
  'Hôm nay học chăm, mai khoe với tương lai.',
  'KPI hôm nay: Không bỏ cuộc.',
  'Nếu lười có huy chương thì Phương đang từ chối nhận. 😆',
  'Chỉ cần thêm vài dòng ghi chú nữa thôi.',
  'Não đang nhảy múa vì dopamine từ việc hoàn thành bài học.',
  'BA tương lai không được đầu hàng nha.',
  'Mỗi lần học là một lần "hack" cuộc đời.',
  'Phương đang làm điều mà tương lai sẽ cảm ơn.',
  'Trời không phụ người chăm chỉ.',
  'Chỉ cần em không bỏ cuộc là anh vui rồi.',
  'Chúc mừng! Não vừa mở khóa thêm một nếp nhăn.',
  'Học đi, sau này còn flex CV.',
  'Một ngày nào đó em sẽ cười vì hôm nay không bỏ cuộc.',
  'Chương này sắp bị Phương đánh bại rồi.',
  'Nếu bài học biết nói, nó sẽ xin hàng.',
  'Hôm nay học giỏi, mai ngủ ngon.',
  'Đừng quên uống nước, não cũng khát.',
  'Trà sữa chỉ ngon hơn khi học xong.',
  'Bài tập khó? Chỉ là fan của Phương thôi.',
  'Não gửi yêu cầu: "Đừng mở Facebook."',
  'Em đang thắng chính mình.',
  'Người đẹp học giỏi luôn hiếm.',
  'Nhưng Phương thì ngoại lệ.',
  'Chỉ cần thêm 5 phút thần kỳ.',
  'Hôm nay em rất ngầu.',
  'Đừng để chiếc giường dụ dỗ.',
  'Một BA giỏi bắt đầu từ hôm nay.',
  'Bài học này không sống sót nổi trước Phương đâu.',
  'Anh vote 5 sao cho sự chăm chỉ của em.',
  'Tương lai vừa gửi icon 👍.',
  'Chỉ số "xinh + chăm" đang quá cao.',
  'Học tiếp đi, em đang có streak đẹp lắm.',
  'Nếu mệt thì nghỉ 5 phút, đừng nghỉ luôn nha.',
  'Mỗi dòng note đều đáng giá.',
  'Não vừa nói "good job!"',
  'Chương này chuẩn bị bị "clear".',
  'Em là MVP của hôm nay.',
  'Có người đang âm thầm cổ vũ em mỗi ngày.',
  'Học xong nhớ tự thưởng nhé.',
  'Một chiếc BA đang dần xuất hiện.',
  'Chúc mừng! Không ngủ gật là thành công rồi.',
  'Hôm nay em đáng yêu, mai còn đáng yêu hơn.',
  'Đừng để deadline cười vào mặt mình.',
  'Chỉ thêm một ví dụ nữa thôi.',
  'Mỗi lần em cố gắng là một lần tương lai mỉm cười.',
  'Anh gửi +100 động lực cho Phương.',
  'Não đang xin thêm dữ liệu.',
  'Cố lên, chiếc CV tương lai đang được nâng cấp.',
  'Em chính là nhân vật chính của câu chuyện này.',
  'Hôm nay chăm chỉ, mai tự tin.',
  'Đừng quên mỉm cười với chính mình.',
  'Anh tin Phương hơn cả Wi-Fi tin mật khẩu.',
  'Chỉ cần học thêm chút nữa, boss cuối sắp thua.',
  'Bài học này sắp phải gọi em là "sư phụ".',
  'Một nụ cười + một trang tài liệu = ngày tuyệt vời.',
  'Phương vừa nhận buff "Không Bỏ Cuộc". ✨',
  'Còn vài phút nữa thôi, em làm được!',
  'Kết thúc phiên học này, nhớ tự nói với mình: "Mình giỏi phết đấy!" 💕',
]

/** 100 random-flavored one-liners (gaming / anime / café / BA in-jokes). */
export const CHEERS_RANDOM: string[] = [
  '💕 Anh vừa kiểm tra... hình như Phương dễ thương hơn sau mỗi 10 phút học.',
  '🤖 [System]: Focus detected. +20 Knowledge, +10 Confidence.',
  '🐱 Meow! Tui canh laptop giúp rồi, Phương học tiếp nha.',
  '☕ Barista báo: Latte nóng đã sẵn sàng, deadline cũng vậy.',
  '🎮 Quest: Hoàn thành 5 trang tài liệu. Reward: +150 XP.',
  '😂 Stakeholder đồng ý rồi... trong giấc mơ thôi. Học tiếp nào!',
  '🌸 Paimon nói: "Đi học trước rồi hẵng đi khám phá!"',
  '💕 Anh không giục đâu... chỉ nhớ cô BA tương lai thôi.',
  '🤖 AI Prediction: Phương có 98.7% khả năng hoàn thành chương này.',
  '🐶 Gâu! Tui giữ chỗ ngồi giúp rồi nè.',
  '😂 Excel vừa mở, não cũng nên mở luôn nha.',
  '🎮 Achievement Unlocked: Không mở TikTok trong 20 phút.',
  '☕ Quán hôm nay giảm giá... nếu học xong chương này.',
  '🌸 Nếu đây là anime thì đây chính là arc luyện tập.',
  '💕 Cố thêm chút nữa nha, anh tin em.',
  '🤖 Battery của laptop còn 65%. Động lực của Phương nên là 100%.',
  '🐱 Mèo nói: "Đừng vuốt tui nữa, vuốt tài liệu đi."',
  '😂 Requirement không tự viết đâu nha.',
  '🎮 Boss "Lười Biếng Lv.99" đang chờ.',
  '🌸 Main character không bỏ cuộc giữa tập đâu.',
  '💕 Học xong anh thưởng một lời khen thật to.',
  '☕ Cappuccino: "Tôi giữ tỉnh táo, còn Phương giữ quyết tâm."',
  '🤖 Sync thành công: Động lực +100.',
  '🐹 Capybara gửi cái ôm bình tĩnh 🫂.',
  '😂 Jira không có nút "Auto Complete" đâu.',
  '🎮 Combo x2! Hai phiên Pomodoro liên tiếp.',
  '🌸 "Ganbatte, Phương-chan!" ✨',
  '💕 Anh thích nhìn em chăm chỉ hơn bất cứ điều gì.',
  '🤖 Loading... Đang cài đặt BA Professional Pack.',
  '🐶 Corgi đã ngồi nghiêm túc chờ em học xong.',
  '😂 Stakeholder: "Thêm một thay đổi nhỏ..." 💀',
  '🎮 HP đầy, Mana đầy, chỉ thiếu học tiếp.',
  '☕ Espresso bảo: "Tỉnh rồi thì học luôn."',
  '🌸 Arc này hơi khó nhưng nhân vật chính sẽ thắng.',
  '💕 Em học đi, anh lo phần cổ vũ.',
  '🤖 Mission Update: Còn 12 phút nữa thôi.',
  '🐱 Mèo xác nhận: Em giỏi hơn hôm qua.',
  '😂 Requirement rõ ràng là hạnh phúc của BA.',
  '🎮 Critical Hit! Hiểu bài ngay lần đầu.',
  '☕ Barista bonus: Một nụ cười miễn phí 😊.',
  '💕 Có người đang rất tự hào về em.',
  '🤖 Aura +999 sau mỗi chương hoàn thành.',
  '🐱 Meow! Đừng để sách buồn nha.',
  '😂 Excel không đáng sợ bằng deadline.',
  '🎮 Save game trước khi nghỉ giải lao.',
  '🌸 Chỉ cần cố thêm một chút thôi.',
  '💕 Anh gửi em +100 Luck hôm nay.',
  '☕ Trà đào bảo: "Đừng quên uống nước."',
  '🤖 Focus Streak: 43 phút. Tuyệt vời!',
  '🐶 Corgi đang vẫy đuôi cổ vũ.',
  '😂 Bug trong code còn dễ hơn bug trong Requirement.',
  '🎮 EXP +50 vì ghi chú cẩn thận.',
  '🌸 Đây là phân cảnh khiến ai cũng ngưỡng mộ.',
  '💕 Em chỉ cần tiếp tục, phần còn lại để thời gian lo.',
  '☕ Americano nói: "Đừng ngủ nha."',
  '🤖 AI xác nhận: Phương đang rất ngầu.',
  '🐱 Tui bắt được con "Lười". Em học tiếp đi.',
  '😂 Scope creep vừa bị đuổi khỏi dự án.',
  '🎮 Skill mới mở khóa: Active Listening.',
  '🌸 Một chương nữa thôi!',
  '💕 Anh vẫn ở đây cổ vũ em.',
  '🤖 Progress: ████████░░ 80%.',
  '🐶 Corgi mang dép đến giờ nghỉ rồi.',
  '☕ Latte Art hình trái tim dành cho Phương ❤️.',
  '😂 "Chỉ sửa một chút thôi." — câu nói đáng sợ nhất.',
  '🎮 Side Quest: Đứng dậy vươn vai.',
  '🌸 Nhân vật chính luôn học trước khi tỏa sáng.',
  '💕 Học xong nhớ tự thưởng nha.',
  '🤖 Dopamine vừa tăng +15.',
  '🐱 Mèo gửi huy hiệu "Siêu Chăm Chỉ".',
  '😂 Excel đã lưu. Phương cũng nhớ Ctrl + S nhé.',
  '🎮 Rare Item nhận được: Một ý tưởng hay.',
  '☕ Quán đóng cửa lúc em học xong thôi.',
  '🌸 Chúc mừng! Em vừa mạnh hơn phiên bản 30 phút trước.',
  '💕 Anh cá là em sẽ làm được.',
  '🤖 Mood Detector: Phát hiện cần một nụ cười 😊.',
  '🐹 Capybara mang bánh quy đến 🍪.',
  '😂 User Story: "Là Phương, tôi muốn học xong để đi ngủ ngon."',
  '🎮 Combo 3 phiên học! Legendary!',
  '🌸 Đừng bỏ qua sức mạnh của từng bước nhỏ.',
  '💕 Em là BA tương lai mà anh luôn tin tưởng.',
  '🤖 Achievement: Focus Master I.',
  '🐱 Mèo ngủ rồi, còn em học nhé.',
  '☕ Barista: "Hết cà phê nhưng chưa hết động lực."',
  '😂 BA không đọc Requirement thì giống đầu bếp quên muối.',
  '🎮 HP giảm? Dùng kỹ năng "Nghỉ 5 phút".',
  '🌸 Em đang viết nên tập hay nhất của cuộc đời mình.',
  '💕 Anh thích thấy em cười sau mỗi lần hoàn thành mục tiêu.',
  '🤖 Scan hoàn tất: Không phát hiện dấu hiệu bỏ cuộc.',
  '🐶 Corgi trao huy chương "Người Chăm Nhất Hôm Nay".',
  '😂 Requirement rõ như nước hồ Gươm... lúc trời mưa.',
  '🎮 Boss cuối chỉ còn 5% HP.',
  '☕ Đồ uống hôm nay miễn phí... nếu em tự khen mình.',
  '🌸 Phương-chan, cố lên! ✨',
  '💕 Một ngày nào đó em sẽ cảm ơn chính mình vì hôm nay.',
  '🤖 Final Check: Confidence Level = MAX.',
  '🐱 Meow! Học xong tui dẫn đi ngủ.',
  '😂 Sprint này chỉ còn một task nữa thôi!',
  '🎮 Victory! Chương học đã bị đánh bại.',
  '💖 Nhiệm vụ hôm nay hoàn thành. Người tự hào nhất về Phương... chính là Phương của ngày mai.',
]

/** The full pool the study companion draws random cheers from. */
export const ALL_CHEERS: string[] = [...CHEERS_WARM, ...CHEERS_FUNNY, ...CHEERS_RANDOM]

/** Gentle, reassuring lines — used when a quiz doesn't pass, so the tone fits. */
export const REASSURE: string[] = [
  'Đừng sợ sai, vì mỗi lần sai là một lần học.',
  'Đừng lo nếu chưa hiểu ngay, rồi sẽ hiểu thôi.',
  'Không ai giỏi ngay từ đầu cả.',
  'Đừng để một bài khó làm em nản lòng.',
  'Đừng để khó khăn làm em chùn bước.',
  'Không cần hoàn hảo, chỉ cần không dừng lại.',
  'Đừng sợ sai. Excel cũng đầy lỗi mà vẫn nổi tiếng.',
  'Mỗi lần học là một lần trưởng thành.',
  'Chỉ cần em không bỏ cuộc.',
  'Xem lại một chút rồi thử lại nhé, em làm được mà. 🌸',
]
